### ISSUE TITLE
Code for testing and training

### ISSUE THREAD

**Issue by shriarul5273** [DefaultRui/VLN-VER#2]
Interesting Work, :smile:   Can you please share the training and testing code  for the paper ?

**Comment by DefaultRui** [comment]
Thanks for your interest in our work! Now I open source the details of VER training.

**Comment by shriarul5273** [comment]
Thank you, so much :+1:

**Comment by quhongyu** [comment]
@shriarul5273 I noticed that the link to object annotations and occupancy labels seems to be invalid now.
Could you please share the annotations with me? It would be really helpful for reproducing the results.
